### ISSUE TITLE
Add the ability for users to interact with 'WMS' vector data layer attributes

### ISSUE THREAD

**Issue by dubwalla** [WFP-VAM/prism-frontend#134]
Some data layers of the type 'WMS' have underlying vector data (as opposed to the previous WMS layers which were raster). PRISM should allow interaction with vector data in 'WMS' layers. Similar to the way we've used WCS to access GeoTIFFs, the underlying vector data is available through WFS. These layers have data attributes which should be accessible through PRISM's UI.

For example, [this WFS request](https://geonode.wfp.org/geoserver/wfs/?service=wfs&version=2.0.0&request=GetFeature&typeNames=prism%3Awld_ibtracs&outputFormat=application/json&time=2021-01-27) returns a collection of points with multiple data fields. We need to 1) allow the configuration of these layers to specify which attributes should be shown to users and 2) allow a user to click (or hover?) on the layer and see those data attributes in a tooltip.

This relates to integration of ADAM data layers via WFP's GeoNode (PR #132).

**Comment by dubwalla** [comment]
@reed1 - please have a look and propose a solution that we can discuss with @ericboucher

**Comment by dubwalla** [comment]
@reed1 - please share what you've done on this in a new branch. Thanks!

**Comment by reed1** [comment]
Hi Amit, I put the changes to [wmsvector-ridwan](https://github.com/WFP-VAM/prism-frontend/tree/wmsvector-ridwan) branch. Now the point_data layer can have WMS url, but additional attribute is needed which I put as dataFormat (base | wms), all implementation of point_data layer previously is categorized as 'base' format and the url needs to be changed to include date format between brackets to avoid hardcoding params on js. Here's how it looks:

![thumbnail_image001](https://user-images.githubusercontent.com/1814324/113259183-0ac21100-92f7-11eb-8f22-b54ca545c23c.png)

The tooltip will work as normal and the value will be taken from `measure` attribute on `layer.json` but since the example points don't intersect with boundary layer, the tooltip will not show. For more customizable popup content and interactivity, it has been implemented on idn_dev branch #137 I can make a separate branch for pull request if needed

**Comment by dubwalla** [comment]
Thanks @reed1 . @JorgeMartinezG also has some thoughts on another way to solve for this. Jorge - please add your thoughts here when you can
