### ISSUE TITLE
Implement labels for legend values

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-frontend#320]
Currently we decipher values from the legend text to generate 'stops' for the color ramp displayed. However, this limits our ability to write meaningful labels for the legend text. We should instead add an attribute for the legend which is specifically a label in addition to the value attribute.

**Comment by reed1** [comment]
This was implemented in idn_dev branch [commit](https://github.com/WFP-VAM/prism-frontend/commit/ef5e001f7dd13d89f13172049f7851eae52d831a). Basically adding `label?: string` as an optional property on `LegendDefinitionItem`. If the `label` property is defined, then it will be shown instead of `value` property. 

Another approach would be to modify the `LegendDefinitionItem` to `{ label: string, color: string, stop?: number }`, to signify that the `stop` property is used to render color on admin_level_data layer, thus the `label` property is always used for legend's label. The typing is clearer too since it doesn't use union types `value: string | number`, but the json configs need to be changed as well.

Sorry that the commit was mixed up with other things, I can make a separate PR for this

**Comment by wadhwamatic** [comment]
@reed1 - Yes, let's please try to make a PR which addresses this issue specifically. I'm trying to find a pathway to get additional features developed in Indonesia tested and merged for all deployments. The best way to do this will be small incremental PRs. Hope that's clear

**Comment by wadhwamatic** [comment]
re: the approach, let's go with label, value and color. No need to introduce 'stop'.

**Comment by wadhwamatic** [comment]
addressed with https://github.com/WFP-VAM/prism-frontend/pull/327
