### ISSUE TITLE
Add map positioning as a URL attribute; keep consistent when loading new layers

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-frontend#342]
I've been meaning to write this one for a while. Resetting the map position whenever we load a new layer is frustrating. A user may have zoomed / panned to a specific area of interest but then loses that positioning by activating a new layer. Building off of the URL parsing feature (https://github.com/WFP-VAM/prism-frontend/pull/255), let's also add the necessary attributes (zoom and lat/long center position) to directly link to a specific view.

**Comment by ericboucher** [comment]
@wadhwamatic I think there are two different issues here:

1. the map position should not be reset whenever we load a new layer
2. the url parser should accept position and zoom so that users can share a link to a specific view. A caveat is that the view depends from the browser/screen size as well. Eg. the result will be very different on a desktop and mobile.

**Comment by wadhwamatic** [comment]
Yeah, agreed. I'll create two separate issues and close this one

**Comment by wadhwamatic** [comment]
Closing this issue. Refer instead to https://github.com/WFP-VAM/prism-frontend/issues/345 and https://github.com/WFP-VAM/prism-frontend/issues/346
