### ISSUE TITLE
Kobo forms - choosing a new date fails to load data

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-frontend#552]
If a user chooses a WMS layers followed by a kobo layer, then deselects the WMS layer, date selection no longer works on the kobo layer.

Steps to reproduce:
1. On master, REACT_APP_COUNTRY=cambodia
2. Activate layer Rainfall amount > Rainfall aggregate 10-day
3. Activate layer Exposure > Flood report
4. De-activate rainfall aggregate layer
5. From the date picker, choose another date. The URL correctly updates, but no request is sent and no data is loaded

All ok through step 3:
<img width="1440" alt="Screen Shot 2022-08-29 at 18 12 42" src="https://user-images.githubusercontent.com/3343536/187326235-884795c8-c33b-43be-a973-19d8ae63e56a.png">

This is what I see for the date picker after de-activating the WMS layer (step 4):
<img width="1438" alt="Screen Shot 2022-08-29 at 18 13 19" src="https://user-images.githubusercontent.com/3343536/187326355-52bbfc77-f604-467e-bb94-34bf3770ba49.png">

After step 5, no data is loaded. Note the URL is correctly updated to Aug 10, but no request is sent (confirmed in the network tool)
<img width="1440" alt="Screen Shot 2022-08-29 at 18 13 42" src="https://user-images.githubusercontent.com/3343536/187326453-217ba7cb-e21b-4528-bd3b-afc37c431bd2.png">

cc @ericboucher

**Comment by JorgeMartinezG** [comment]
Checking this issue, PRISM has an internal cache for storing layer data. If the data for a given date has been previously stored, PRISM will read from the cache instead of making a request to the remote server. This is why the request is not shown in the network tab.

However, some requests take long time and there is no indicator on PRISM to let the user know about this. There is a feeling that nothing is happening in the platform. One possible solution is to include a circular progress, to show that data is loading.

**Comment by wadhwamatic** [comment]
@JorgeMartinezG - this wasn't a time out issue. I waited several minutes and nothing happened consistently.
