### ISSUE TITLE
New UI/Functionality for Legend Dropdown

### ISSUE THREAD

**Issue by Ry-DS** [WFP-VAM/prism-frontend#82]
The current Legend button:
![image](https://user-images.githubusercontent.com/25571542/84863247-01452080-b0b8-11ea-90c4-e1e2bb38f2aa.png)
Could use some improvement, notably in its style and functionality. 

Ideas: 
1. The Hide/Show button could be styled to fit more into a Material UI theme, making it complement the switches.

2. It could also be converted to a drop-down style, replacing the 'eye' with a chevron arrow.

3. We could add crosses on every legend section so a user can quickly remove a layer by clicking the cross on the layer's legend.

**Comment by ericboucher** [comment]
Good ideas!

I like 1 and 3 a lot, but I think the `eye` works pretty well though and it's easy to guess what it's doing.

@dubwalla do you have any additional feedback?

**Comment by dubwalla** [comment]
Yes, agreed that 1 and 3 are great suggestions. I was thinking that instead of 'removing' a layer, a toggle would be good so that a user can activate or deactivate a layer without having to expand the top nav again. 

It's also worth thinking about having the ability to hide / collapse a legend entry like suggested in 2, but at the individual layer level. An opacity slider at the layer level is also handy to have.

Not to complicate this issue, but also worth mentioning that we also need a UI solution for showing a table view of a layer and to download the layer directly. I was thinking this could be within what is currently the legend area. We can make this a separate issue though
