### ISSUE TITLE
Create a separate UI for invoking an analysis 

### ISSUE THREAD

**Issue by dubwalla** [WFP-VAM/prism-frontend#86]
With the addition of new API requests to fetch an analysis output, we need a new UX / UI which is differentiated from the standard layer views. A user needs to: 

1. Configure an analysis
2. Run the analysis
3. Receive an indication of the analysis job's status
4. View the results as a map or table
5. Download the results

Some rough ideas below but please suggest options / alternatives.

Separate UI element to run an analysis
<img width="224" alt="Screenshot 2020-06-19 18 16 26" src="https://user-images.githubusercontent.com/3343536/85188068-01305680-b259-11ea-933f-d78910704811.png">

Analysis pane activated:
<img width="492" alt="Screenshot 2020-06-19 18 18 00" src="https://user-images.githubusercontent.com/3343536/85188084-3a68c680-b259-11ea-8253-eaccc91eb8b8.png">

After staring an analysis job, some user awareness of status:
<img width="326" alt="Screenshot 2020-06-19 18 18 59" src="https://user-images.githubusercontent.com/3343536/85188105-697f3800-b259-11ea-8b52-377d0d00179d.png">

Buttons active when the analysis job is complete. User can view or download the results:
<img width="318" alt="Screenshot 2020-06-19 18 19 53" src="https://user-images.githubusercontent.com/3343536/85188131-93385f00-b259-11ea-9bba-7aada2fe85e2.png">

View the results as a map:
<img width="1054" alt="Screenshot 2020-06-19 18 21 11" src="https://user-images.githubusercontent.com/3343536/85188188-ad723d00-b259-11ea-9d4f-69efd07ec742.png">

View the results as a table:
<img width="517" alt="Screenshot 2020-06-19 18 21 41" src="https://user-images.githubusercontent.com/3343536/85188200-be22b300-b259-11ea-9e9e-59faa3999621.png">

**Comment by SimplyBallistic** [comment]
The API I currently see from #80 is for zonal statistics. Is there a new one that could be used to calculate the map and table data? If so, how might one use it in relation to all the fields listed here? If this API is still a WIP, we can work on creating the barebones UI and make some fake filler functions that return filler JSON that can later be replaced with the actual API calls.

To make it more obvious the analysis has completed, we can leverage #87 here to create a notification once the analysis is done.

**Comment by SimplyBallistic** [comment]
What about using dropdowns instead of radio buttons? Since we don't have a lot of space to work with, a dropdown could help simplify the menu a little and also help ensure future layers don't break the menu somehow by taking more space.

We could keep radio buttons for the statistic type.

**Comment by dubwalla** [comment]
Good suggestion to use dropdowns. The mockups were just to show what was happening in terms of flow. Definitely prefer an implementation that will work regardless of number of available layers, analysis types, etc.

**Comment by SimplyBallistic** [comment]
I thought it would be neat to click a table row and for the corresponding tooltip to open on the map, so I made it here:

https://github.com/oviohub/prism-frontend/pull/92/commits/d7e9d2186887615aeac0f9c14133054a04f660d3

without putting too much effort into actually displaying meaningful data in the tooltip (mostly a proof-of-concept).

Should we try make it a proper feature?

There are some caveats - its really hard to make the tooltip appear in the middle of a state since we only have boundary points, so the tooltip is always on a boundary. We could put in the effort to run a calculation to find the middle?

**Comment by laveesh** [comment]
I thought this mockup to show the analysis to user so that is easy for him to see the current details for which the analysis is created.

**UX Design:**
- Currently, _RUN ANALYSIS_ and _DOWNLOAD_ buttons are at the end of the table, so the user has to scroll down to click them
- New, All these buttons would be stick to the footer 
- The summary would be scrollable for the user

![Analysis Mock up](https://user-images.githubusercontent.com/31915056/87220750-52c59000-c384-11ea-9cee-baa562b5e9e2.png)

**Comment by dubwalla** [comment]
> I thought it would be neat to click a table row and for the corresponding tooltip to open on the map,

Great idea Ryan! I definitely find it useful to have interaction between the table and map view. It would be great to have this implemented, with the tooltip in the center of the polygon as you suggested. Not a high priority at the moment, but a great feature to have.

**Comment by dubwalla** [comment]
> I thought this mockup to show the analysis to user so that is easy for him to see the current details for which the analysis is created.
> 
> **UX Design:**
> 
> * Currently, _RUN ANALYSIS_ and _DOWNLOAD_ buttons are at the end of the table, so the user has to scroll down to click them
> * New, All these buttons would be stick to the footer
> * The summary would be scrollable for the user
> 
> ![Analysis Mock up](https://user-images.githubusercontent.com/31915056/87220750-52c59000-c384-11ea-9cee-baa562b5e9e2.png)

Yes, this is a good suggestion. +1 from me to implement this
