### ISSUE TITLE
Link to an analysis or a view

### ISSUE THREAD

**Issue by ericboucher** [WFP-VAM/prism-frontend#89]
## Idea

Allow users to share a link to a specific analysis / selection / view

**Comment by dubwalla** [comment]
Yes, definitely need this in our roadmap. We eventually need to support an alert system which generates an email / message to a user that draws them into PRISM with a specific view

**Comment by SimplyBallistic** [comment]
Since redux state is serialized, you might be able to export a snapshot of the state as base64 and pass it around as a link?

**Comment by ericboucher** [comment]
I was thinking something `simpler`. Rather than transferring the state, we should be able to link to an analysis by its parameters in the URL like this:

`prim_url.org/analysis?hazard_layer=pasture_anomaly&statistic=mean&basline_layer=children&date=2020-05-21`

**Comment by dubwalla** [comment]
While we are doing this, can we make this apply to views more broadly, and not just an analysis? I.e. also load a specified view based on URL parameters: prim_url.org/view?hazard_layer=pasture_anomaly&date=2020-05-21

**Comment by Ry-DS** [comment]
## Update 2021
Several PRs have attempted to solve this issue, but didn't follow the kind of pattern we were hoping for. You can view them here:
- #103
- #120 

We hope to build an approach which is both scalable (as new fields get added, little to no extra work is needed to update this code) and also simple/modular (we could eventually extend this code to support new types of layers as they come).

### Requirements:
- The URL query is created dynamically - we shouldn't be hard coding the query like what is done [here.](https://github.com/WFP-VAM/prism-frontend/pull/120/files#diff-314a2832937cda41c6f51176b41683977e412b5dc6b10d8ffff85ffa2f293bd1R197)
    - This can be done by storing the fields inside an object instead of in separate state fields. A single `useState` or `useReducer` - complex but might be worthwhile if you can think of a lot of actions to update from url, edit fields etc - should be used to store the whole field state.
- The analysis dropdown opens if there is a valid query, with all fields filled in.
- There is an error checker. Nothing advanced, but if there's something obviously wrong with the url we can create a notification with the notification state slice.

### Tips:
- I recommend `useReducer` since I envision many actions we can easily encapsulate such as `urlToState`, `stateToUrl`, `updateField` etc. However, until we put into practise we won't know if its really any better than a simple `useState`. It'll be up to you to experiment!
- In the future, we'd like for these url queries to also open layers for us. For example, a user should be able to open a layer, select a date, copy the address field and share it so others can instantly jump to the same layer. Keep this in mind, since we need a solution that applies well in both cases (analysis UI and opening layers).
- You could *maybe* use a library: https://github.com/pbeshai/use-query-params, but I haven't looked into whether it fits our use-case. If you see it working well for both cases mentioned above, maybe we can save some time and complexity by using it.

**Comment by wadhwamatic** [comment]
Bumping up in priority. This is something we need for meaningful alert messages

**Comment by wadhwamatic** [comment]
Addressed through https://github.com/WFP-VAM/prism-frontend/pull/255
